// Code generated by protoc-gen-go. DO NOT EDIT.
// source: etcd.proto

package etcd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace            string            `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Version              map[string]string `protobuf:"bytes,4,rep,name=Version,proto3" json:"Version,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ports                []*Port           `protobuf:"bytes,5,rep,name=Ports,proto3" json:"Ports,omitempty"`
	MeshExternal         bool              `protobuf:"varint,6,opt,name=MeshExternal,proto3" json:"MeshExternal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcd_c13f1d0310f3b895, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Service) GetVersion() map[string]string {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Service) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Service) GetMeshExternal() bool {
	if m != nil {
		return m.MeshExternal
	}
	return false
}

type Port struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Protocol             string   `protobuf:"bytes,3,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcd_c13f1d0310f3b895, []int{1}
}
func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (dst *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(dst, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Port) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type Node struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Az                   string            `protobuf:"bytes,3,opt,name=Az,proto3" json:"Az,omitempty"`
	Users                map[string]string `protobuf:"bytes,4,rep,name=Users,proto3" json:"Users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcd_c13f1d0310f3b895, []int{2}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetAz() string {
	if m != nil {
		return m.Az
	}
	return ""
}

func (m *Node) GetUsers() map[string]string {
	if m != nil {
		return m.Users
	}
	return nil
}

type Instance struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ServiceId            string            `protobuf:"bytes,2,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	ServiceVersion       string            `protobuf:"bytes,3,opt,name=ServiceVersion,proto3" json:"ServiceVersion,omitempty"`
	NodeId               string            `protobuf:"bytes,4,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Port                 *Port             `protobuf:"bytes,5,opt,name=Port,proto3" json:"Port,omitempty"`
	Labels               map[string]string `protobuf:"bytes,6,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcd_c13f1d0310f3b895, []int{3}
}
func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (dst *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(dst, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Instance) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

func (m *Instance) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Instance) GetPort() *Port {
	if m != nil {
		return m.Port
	}
	return nil
}

func (m *Instance) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Cluster struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ServiceId            string            `protobuf:"bytes,2,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	InstanceIds          map[string]string `protobuf:"bytes,3,rep,name=InstanceIds,proto3" json:"InstanceIds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcd_c13f1d0310f3b895, []int{4}
}
func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (dst *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(dst, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cluster) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Cluster) GetInstanceIds() map[string]string {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

func (m *Cluster) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "etcd.Service")
	proto.RegisterMapType((map[string]string)(nil), "etcd.Service.VersionEntry")
	proto.RegisterType((*Port)(nil), "etcd.Port")
	proto.RegisterType((*Node)(nil), "etcd.Node")
	proto.RegisterMapType((map[string]string)(nil), "etcd.Node.UsersEntry")
	proto.RegisterType((*Instance)(nil), "etcd.Instance")
	proto.RegisterMapType((map[string]string)(nil), "etcd.Instance.LabelsEntry")
	proto.RegisterType((*Cluster)(nil), "etcd.Cluster")
	proto.RegisterMapType((map[string]string)(nil), "etcd.Cluster.InstanceIdsEntry")
	proto.RegisterMapType((map[string]string)(nil), "etcd.Cluster.LabelsEntry")
}

func init() { proto.RegisterFile("etcd.proto", fileDescriptor_etcd_c13f1d0310f3b895) }

var fileDescriptor_etcd_c13f1d0310f3b895 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x8b, 0xd3, 0x50,
	0x14, 0x25, 0x2f, 0x1f, 0x6d, 0x6f, 0xc7, 0x61, 0xb8, 0xa8, 0x3c, 0xc3, 0x30, 0x84, 0x2c, 0xa4,
	0x20, 0x04, 0x1c, 0x5d, 0x8c, 0xb3, 0x10, 0x8b, 0x74, 0x11, 0xd1, 0x52, 0x22, 0xba, 0x4f, 0x93,
	0x07, 0x16, 0x63, 0x12, 0xde, 0x4b, 0x8b, 0xed, 0xd6, 0x85, 0xbf, 0xc2, 0xb5, 0x7f, 0x53, 0xde,
	0x47, 0xda, 0xb4, 0x76, 0x13, 0x66, 0xd5, 0x77, 0xcf, 0xfd, 0x3a, 0xe7, 0xdc, 0x12, 0x00, 0xd6,
	0x64, 0x79, 0x54, 0xf3, 0xaa, 0xa9, 0xd0, 0x91, 0xef, 0xf0, 0x17, 0x81, 0xc1, 0x67, 0xc6, 0x37,
	0xab, 0x8c, 0xe1, 0x25, 0x90, 0x38, 0xa7, 0x56, 0x60, 0x4d, 0x46, 0x09, 0x89, 0x73, 0x44, 0x70,
	0xe6, 0xe9, 0x0f, 0x46, 0x89, 0x42, 0xd4, 0x1b, 0xaf, 0x61, 0x24, 0x7f, 0x45, 0x9d, 0x66, 0x8c,
	0xda, 0x2a, 0x71, 0x00, 0xf0, 0x35, 0x0c, 0xbe, 0x32, 0x2e, 0x56, 0x55, 0x49, 0x9d, 0xc0, 0x9e,
	0x8c, 0x6f, 0xfd, 0x48, 0x6d, 0x34, 0x1b, 0x22, 0x93, 0x9c, 0x95, 0x0d, 0xdf, 0x26, 0x6d, 0x29,
	0x06, 0xe0, 0x2e, 0x2a, 0xde, 0x08, 0xea, 0xaa, 0x1e, 0xd0, 0x3d, 0x12, 0x4a, 0x74, 0x02, 0x43,
	0xb8, 0xf8, 0xc4, 0xc4, 0xb7, 0xd9, 0xcf, 0x86, 0xf1, 0x32, 0x2d, 0xa8, 0x17, 0x58, 0x93, 0x61,
	0x72, 0x84, 0xf9, 0xf7, 0x70, 0xd1, 0x1d, 0x8f, 0x57, 0x60, 0x7f, 0x67, 0x5b, 0x23, 0x47, 0x3e,
	0xf1, 0x31, 0xb8, 0x9b, 0xb4, 0x58, 0xb7, 0x82, 0x74, 0x70, 0x4f, 0xee, 0xac, 0xf0, 0x03, 0x38,
	0x72, 0xd1, 0x5e, 0xb1, 0xd5, 0x51, 0x8c, 0x3a, 0xa7, 0x9a, 0x1e, 0x25, 0xba, 0xce, 0x87, 0xe1,
	0x42, 0x9a, 0x98, 0x55, 0x85, 0x31, 0x61, 0x1f, 0x87, 0x7f, 0x2c, 0x70, 0xe6, 0x55, 0xfe, 0xbf,
	0x9d, 0x32, 0xae, 0xcd, 0x6e, 0x12, 0xd7, 0x32, 0x9e, 0xee, 0x4c, 0x3b, 0x99, 0xee, 0xf0, 0x05,
	0xb8, 0x5f, 0x04, 0xe3, 0xc2, 0x58, 0xf7, 0x44, 0xdb, 0x20, 0x47, 0x45, 0x0a, 0xd7, 0xae, 0xe9,
	0x1a, 0xff, 0x0e, 0xe0, 0x00, 0xf6, 0xd2, 0xfa, 0x9b, 0xc0, 0x30, 0x2e, 0x45, 0x93, 0x96, 0x67,
	0x4e, 0x7e, 0x0d, 0x23, 0x73, 0xab, 0x38, 0x37, 0xad, 0x07, 0x00, 0x9f, 0xc3, 0xa5, 0x09, 0xda,
	0x2b, 0x6b, 0xf6, 0x27, 0x28, 0x3e, 0x05, 0x4f, 0xd2, 0x8e, 0x73, 0xea, 0xa8, 0xbc, 0x89, 0xf0,
	0xc6, 0x58, 0xe9, 0x06, 0xd6, 0xc9, 0x9d, 0xb5, 0xad, 0xb7, 0xe0, 0x7d, 0x4c, 0x97, 0xac, 0x10,
	0xd4, 0xeb, 0xfe, 0x7b, 0x5a, 0xb6, 0x91, 0x4e, 0x6a, 0x1f, 0x4c, 0xa5, 0xff, 0x06, 0xc6, 0x1d,
	0xb8, 0x97, 0x13, 0x7f, 0x09, 0x0c, 0xde, 0x17, 0x6b, 0xd1, 0x30, 0xde, 0xd3, 0x88, 0x77, 0x30,
	0x6e, 0x49, 0xc5, 0xb9, 0xa0, 0xb6, 0x62, 0x7b, 0xa3, 0xd9, 0x9a, 0x89, 0x51, 0xa7, 0x40, 0x33,
	0xee, 0xb6, 0xe0, 0xcb, 0xbd, 0x54, 0x7d, 0xed, 0x67, 0xc7, 0xcd, 0xe7, 0x94, 0xbe, 0x85, 0xab,
	0xd3, 0x99, 0x7d, 0xe4, 0x3e, 0xc0, 0xa9, 0xa5, 0xa7, 0x3e, 0x19, 0xaf, 0xfe, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xf2, 0x38, 0x9d, 0xe7, 0x40, 0x04, 0x00, 0x00,
}
